# site properties and page defaults
title: Shayori Bose
subtitle: 
description: As a high school junior passionate about scientific innovation, I aspire to become an oncologist advancing cancer care through AI-driven research, wet-lab experimentation, and clinical translation. I aim to bridge computational discovery and hands-on science to develop data-informed, clinically relevant solutions that transform oncology and improve patient outcomes.
header: images/cover.jpg
footer: images/cover.jpg
proofer: false

# site social media and other links
links:
  email: shayori.bose@gmail.com
  github: shayorib

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
